/*
 * generated by Xtext 2.28.0
 */
package gameOfLife.ui;

import com.google.inject.Injector;
import gameOfLife.ui.internal.GameOfLifeActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GameOfLifeDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GameOfLifeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GameOfLifeActivator activator = GameOfLifeActivator.getInstance();
		return activator != null ? activator.getInjector(GameOfLifeActivator.GAMEOFLIFE_GAMEOFLIFEDSL) : null;
	}

}
