/*
 * generated by Xtext 2.28.0
 */
package gameOfLife.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameOfLifeDSLScopeProvider extends DelegatingScopeProvider {
}
