/**
 * generated by Xtext 2.28.0
 */
package gameOfLife.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gameOfLife.GameOfLifeDSLRuntimeModule;
import gameOfLife.GameOfLifeDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GameOfLifeDSLIdeSetup extends GameOfLifeDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    GameOfLifeDSLRuntimeModule _gameOfLifeDSLRuntimeModule = new GameOfLifeDSLRuntimeModule();
    GameOfLifeDSLIdeModule _gameOfLifeDSLIdeModule = new GameOfLifeDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_gameOfLifeDSLRuntimeModule, _gameOfLifeDSLIdeModule));
  }
}
