/**
 * generated by Xtext 2.28.0
 */
package gameOfLife.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GameOfLifeDSLIdeModule extends AbstractGameOfLifeDSLIdeModule {
}
