/**
 * generated by Xtext 2.28.0
 */
package gameOfLife;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GameOfLifeDSLRuntimeModule extends AbstractGameOfLifeDSLRuntimeModule {
}
