/*
 * generated by Xtext 2.28.0
 */
package gameOfLife.ui.tests;

import com.google.inject.Injector;
import gameOfLife.ui.internal.GameOfLifeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GameOfLifeDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GameOfLifeActivator.getInstance().getInjector("gameOfLife.GameOfLifeDSL");
	}

}
