/**
 * generated by Xtext 2.28.0
 */
package gameOfLife.gameOfLifeDSL.impl;

import gameOfLife.gameOfLifeDSL.Action;
import gameOfLife.gameOfLifeDSL.ConditionElement;
import gameOfLife.gameOfLifeDSL.EvolutionRule;
import gameOfLife.gameOfLifeDSL.GameOfLifeDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Evolution Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link gameOfLife.gameOfLifeDSL.impl.EvolutionRuleImpl#getConditionElement <em>Condition Element</em>}</li>
 *   <li>{@link gameOfLife.gameOfLifeDSL.impl.EvolutionRuleImpl#getAmount <em>Amount</em>}</li>
 *   <li>{@link gameOfLife.gameOfLifeDSL.impl.EvolutionRuleImpl#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EvolutionRuleImpl extends MinimalEObjectImpl.Container implements EvolutionRule
{
  /**
   * The default value of the '{@link #getConditionElement() <em>Condition Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditionElement()
   * @generated
   * @ordered
   */
  protected static final ConditionElement CONDITION_ELEMENT_EDEFAULT = ConditionElement.LOWER;

  /**
   * The cached value of the '{@link #getConditionElement() <em>Condition Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditionElement()
   * @generated
   * @ordered
   */
  protected ConditionElement conditionElement = CONDITION_ELEMENT_EDEFAULT;

  /**
   * The default value of the '{@link #getAmount() <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmount()
   * @generated
   * @ordered
   */
  protected static final int AMOUNT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getAmount() <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmount()
   * @generated
   * @ordered
   */
  protected int amount = AMOUNT_EDEFAULT;

  /**
   * The default value of the '{@link #getAction() <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAction()
   * @generated
   * @ordered
   */
  protected static final Action ACTION_EDEFAULT = Action.DIE;

  /**
   * The cached value of the '{@link #getAction() <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAction()
   * @generated
   * @ordered
   */
  protected Action action = ACTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EvolutionRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GameOfLifeDSLPackage.Literals.EVOLUTION_RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConditionElement getConditionElement()
  {
    return conditionElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConditionElement(ConditionElement newConditionElement)
  {
    ConditionElement oldConditionElement = conditionElement;
    conditionElement = newConditionElement == null ? CONDITION_ELEMENT_EDEFAULT : newConditionElement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameOfLifeDSLPackage.EVOLUTION_RULE__CONDITION_ELEMENT, oldConditionElement, conditionElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getAmount()
  {
    return amount;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAmount(int newAmount)
  {
    int oldAmount = amount;
    amount = newAmount;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameOfLifeDSLPackage.EVOLUTION_RULE__AMOUNT, oldAmount, amount));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Action getAction()
  {
    return action;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAction(Action newAction)
  {
    Action oldAction = action;
    action = newAction == null ? ACTION_EDEFAULT : newAction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameOfLifeDSLPackage.EVOLUTION_RULE__ACTION, oldAction, action));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.EVOLUTION_RULE__CONDITION_ELEMENT:
        return getConditionElement();
      case GameOfLifeDSLPackage.EVOLUTION_RULE__AMOUNT:
        return getAmount();
      case GameOfLifeDSLPackage.EVOLUTION_RULE__ACTION:
        return getAction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.EVOLUTION_RULE__CONDITION_ELEMENT:
        setConditionElement((ConditionElement)newValue);
        return;
      case GameOfLifeDSLPackage.EVOLUTION_RULE__AMOUNT:
        setAmount((Integer)newValue);
        return;
      case GameOfLifeDSLPackage.EVOLUTION_RULE__ACTION:
        setAction((Action)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.EVOLUTION_RULE__CONDITION_ELEMENT:
        setConditionElement(CONDITION_ELEMENT_EDEFAULT);
        return;
      case GameOfLifeDSLPackage.EVOLUTION_RULE__AMOUNT:
        setAmount(AMOUNT_EDEFAULT);
        return;
      case GameOfLifeDSLPackage.EVOLUTION_RULE__ACTION:
        setAction(ACTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.EVOLUTION_RULE__CONDITION_ELEMENT:
        return conditionElement != CONDITION_ELEMENT_EDEFAULT;
      case GameOfLifeDSLPackage.EVOLUTION_RULE__AMOUNT:
        return amount != AMOUNT_EDEFAULT;
      case GameOfLifeDSLPackage.EVOLUTION_RULE__ACTION:
        return action != ACTION_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (conditionElement: ");
    result.append(conditionElement);
    result.append(", amount: ");
    result.append(amount);
    result.append(", action: ");
    result.append(action);
    result.append(')');
    return result.toString();
  }

} //EvolutionRuleImpl
