/*
 * generated by Xtext 2.28.0
 */
package gameOfLife.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GameOfLifeDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("gameOfLife/parser/antlr/internal/InternalGameOfLifeDSL.tokens");
	}
}
