/**
 * generated by Xtext 2.28.0
 */
package gameOfLife.gameOfLifeDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game Of Life</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameOfLife.gameOfLifeDSL.GameOfLife#getAliveCells <em>Alive Cells</em>}</li>
 *   <li>{@link gameOfLife.gameOfLifeDSL.GameOfLife#getEvolutionRules <em>Evolution Rules</em>}</li>
 * </ul>
 *
 * @see gameOfLife.gameOfLifeDSL.GameOfLifeDSLPackage#getGameOfLife()
 * @model
 * @generated
 */
public interface GameOfLife extends EObject
{
  /**
   * Returns the value of the '<em><b>Alive Cells</b></em>' containment reference list.
   * The list contents are of type {@link gameOfLife.gameOfLifeDSL.Point}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alive Cells</em>' containment reference list.
   * @see gameOfLife.gameOfLifeDSL.GameOfLifeDSLPackage#getGameOfLife_AliveCells()
   * @model containment="true"
   * @generated
   */
  EList<Point> getAliveCells();

  /**
   * Returns the value of the '<em><b>Evolution Rules</b></em>' containment reference list.
   * The list contents are of type {@link gameOfLife.gameOfLifeDSL.EvolutionRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evolution Rules</em>' containment reference list.
   * @see gameOfLife.gameOfLifeDSL.GameOfLifeDSLPackage#getGameOfLife_EvolutionRules()
   * @model containment="true"
   * @generated
   */
  EList<EvolutionRule> getEvolutionRules();

} // GameOfLife
