/**
 * generated by Xtext 2.28.0
 */
package gameOfLife.gameOfLifeDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see gameOfLife.gameOfLifeDSL.GameOfLifeDSLFactory
 * @model kind="package"
 * @generated
 */
public interface GameOfLifeDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gameOfLifeDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.GameOfLifeDSL.gameOfLife";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gameOfLifeDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameOfLifeDSLPackage eINSTANCE = gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link gameOfLife.gameOfLifeDSL.impl.GameOfLifeImpl <em>Game Of Life</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeImpl
   * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getGameOfLife()
   * @generated
   */
  int GAME_OF_LIFE = 0;

  /**
   * The feature id for the '<em><b>Alive Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_OF_LIFE__ALIVE_CELLS = 0;

  /**
   * The feature id for the '<em><b>Evolution Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_OF_LIFE__EVOLUTION_RULES = 1;

  /**
   * The number of structural features of the '<em>Game Of Life</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_OF_LIFE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameOfLife.gameOfLifeDSL.impl.PointImpl <em>Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameOfLife.gameOfLifeDSL.impl.PointImpl
   * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getPoint()
   * @generated
   */
  int POINT = 1;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINT__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINT__Y = 1;

  /**
   * The number of structural features of the '<em>Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameOfLife.gameOfLifeDSL.impl.EvolutionRuleImpl <em>Evolution Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameOfLife.gameOfLifeDSL.impl.EvolutionRuleImpl
   * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getEvolutionRule()
   * @generated
   */
  int EVOLUTION_RULE = 2;

  /**
   * The feature id for the '<em><b>Condition Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVOLUTION_RULE__CONDITION_ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVOLUTION_RULE__AMOUNT = 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVOLUTION_RULE__ACTION = 2;

  /**
   * The number of structural features of the '<em>Evolution Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVOLUTION_RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link gameOfLife.gameOfLifeDSL.ConditionElement <em>Condition Element</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameOfLife.gameOfLifeDSL.ConditionElement
   * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getConditionElement()
   * @generated
   */
  int CONDITION_ELEMENT = 3;

  /**
   * The meta object id for the '{@link gameOfLife.gameOfLifeDSL.Action <em>Action</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameOfLife.gameOfLifeDSL.Action
   * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getAction()
   * @generated
   */
  int ACTION = 4;


  /**
   * Returns the meta object for class '{@link gameOfLife.gameOfLifeDSL.GameOfLife <em>Game Of Life</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Of Life</em>'.
   * @see gameOfLife.gameOfLifeDSL.GameOfLife
   * @generated
   */
  EClass getGameOfLife();

  /**
   * Returns the meta object for the containment reference list '{@link gameOfLife.gameOfLifeDSL.GameOfLife#getAliveCells <em>Alive Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Alive Cells</em>'.
   * @see gameOfLife.gameOfLifeDSL.GameOfLife#getAliveCells()
   * @see #getGameOfLife()
   * @generated
   */
  EReference getGameOfLife_AliveCells();

  /**
   * Returns the meta object for the containment reference list '{@link gameOfLife.gameOfLifeDSL.GameOfLife#getEvolutionRules <em>Evolution Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Evolution Rules</em>'.
   * @see gameOfLife.gameOfLifeDSL.GameOfLife#getEvolutionRules()
   * @see #getGameOfLife()
   * @generated
   */
  EReference getGameOfLife_EvolutionRules();

  /**
   * Returns the meta object for class '{@link gameOfLife.gameOfLifeDSL.Point <em>Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Point</em>'.
   * @see gameOfLife.gameOfLifeDSL.Point
   * @generated
   */
  EClass getPoint();

  /**
   * Returns the meta object for the attribute '{@link gameOfLife.gameOfLifeDSL.Point#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see gameOfLife.gameOfLifeDSL.Point#getX()
   * @see #getPoint()
   * @generated
   */
  EAttribute getPoint_X();

  /**
   * Returns the meta object for the attribute '{@link gameOfLife.gameOfLifeDSL.Point#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see gameOfLife.gameOfLifeDSL.Point#getY()
   * @see #getPoint()
   * @generated
   */
  EAttribute getPoint_Y();

  /**
   * Returns the meta object for class '{@link gameOfLife.gameOfLifeDSL.EvolutionRule <em>Evolution Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evolution Rule</em>'.
   * @see gameOfLife.gameOfLifeDSL.EvolutionRule
   * @generated
   */
  EClass getEvolutionRule();

  /**
   * Returns the meta object for the attribute '{@link gameOfLife.gameOfLifeDSL.EvolutionRule#getConditionElement <em>Condition Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition Element</em>'.
   * @see gameOfLife.gameOfLifeDSL.EvolutionRule#getConditionElement()
   * @see #getEvolutionRule()
   * @generated
   */
  EAttribute getEvolutionRule_ConditionElement();

  /**
   * Returns the meta object for the attribute '{@link gameOfLife.gameOfLifeDSL.EvolutionRule#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see gameOfLife.gameOfLifeDSL.EvolutionRule#getAmount()
   * @see #getEvolutionRule()
   * @generated
   */
  EAttribute getEvolutionRule_Amount();

  /**
   * Returns the meta object for the attribute '{@link gameOfLife.gameOfLifeDSL.EvolutionRule#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see gameOfLife.gameOfLifeDSL.EvolutionRule#getAction()
   * @see #getEvolutionRule()
   * @generated
   */
  EAttribute getEvolutionRule_Action();

  /**
   * Returns the meta object for enum '{@link gameOfLife.gameOfLifeDSL.ConditionElement <em>Condition Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Condition Element</em>'.
   * @see gameOfLife.gameOfLifeDSL.ConditionElement
   * @generated
   */
  EEnum getConditionElement();

  /**
   * Returns the meta object for enum '{@link gameOfLife.gameOfLifeDSL.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Action</em>'.
   * @see gameOfLife.gameOfLifeDSL.Action
   * @generated
   */
  EEnum getAction();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameOfLifeDSLFactory getGameOfLifeDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link gameOfLife.gameOfLifeDSL.impl.GameOfLifeImpl <em>Game Of Life</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeImpl
     * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getGameOfLife()
     * @generated
     */
    EClass GAME_OF_LIFE = eINSTANCE.getGameOfLife();

    /**
     * The meta object literal for the '<em><b>Alive Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_OF_LIFE__ALIVE_CELLS = eINSTANCE.getGameOfLife_AliveCells();

    /**
     * The meta object literal for the '<em><b>Evolution Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_OF_LIFE__EVOLUTION_RULES = eINSTANCE.getGameOfLife_EvolutionRules();

    /**
     * The meta object literal for the '{@link gameOfLife.gameOfLifeDSL.impl.PointImpl <em>Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameOfLife.gameOfLifeDSL.impl.PointImpl
     * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getPoint()
     * @generated
     */
    EClass POINT = eINSTANCE.getPoint();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POINT__X = eINSTANCE.getPoint_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POINT__Y = eINSTANCE.getPoint_Y();

    /**
     * The meta object literal for the '{@link gameOfLife.gameOfLifeDSL.impl.EvolutionRuleImpl <em>Evolution Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameOfLife.gameOfLifeDSL.impl.EvolutionRuleImpl
     * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getEvolutionRule()
     * @generated
     */
    EClass EVOLUTION_RULE = eINSTANCE.getEvolutionRule();

    /**
     * The meta object literal for the '<em><b>Condition Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVOLUTION_RULE__CONDITION_ELEMENT = eINSTANCE.getEvolutionRule_ConditionElement();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVOLUTION_RULE__AMOUNT = eINSTANCE.getEvolutionRule_Amount();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVOLUTION_RULE__ACTION = eINSTANCE.getEvolutionRule_Action();

    /**
     * The meta object literal for the '{@link gameOfLife.gameOfLifeDSL.ConditionElement <em>Condition Element</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameOfLife.gameOfLifeDSL.ConditionElement
     * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getConditionElement()
     * @generated
     */
    EEnum CONDITION_ELEMENT = eINSTANCE.getConditionElement();

    /**
     * The meta object literal for the '{@link gameOfLife.gameOfLifeDSL.Action <em>Action</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameOfLife.gameOfLifeDSL.Action
     * @see gameOfLife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getAction()
     * @generated
     */
    EEnum ACTION = eINSTANCE.getAction();

  }

} //GameOfLifeDSLPackage
