/*
 * generated by Xtext 2.28.0
 */
package gameOfLife.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import gameOfLife.ide.contentassist.antlr.internal.InternalGameOfLifeDSLParser;
import gameOfLife.services.GameOfLifeDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GameOfLifeDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GameOfLifeDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GameOfLifeDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getConditionElementAccess().getAlternatives(), "rule__ConditionElement__Alternatives");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getGameOfLifeAccess().getGroup(), "rule__GameOfLife__Group__0");
			builder.put(grammarAccess.getPointAccess().getGroup(), "rule__Point__Group__0");
			builder.put(grammarAccess.getEvolutionRuleAccess().getGroup(), "rule__EvolutionRule__Group__0");
			builder.put(grammarAccess.getGameOfLifeAccess().getAliveCellsAssignment_2(), "rule__GameOfLife__AliveCellsAssignment_2");
			builder.put(grammarAccess.getGameOfLifeAccess().getEvolutionRulesAssignment_4(), "rule__GameOfLife__EvolutionRulesAssignment_4");
			builder.put(grammarAccess.getPointAccess().getXAssignment_1(), "rule__Point__XAssignment_1");
			builder.put(grammarAccess.getPointAccess().getYAssignment_3(), "rule__Point__YAssignment_3");
			builder.put(grammarAccess.getEvolutionRuleAccess().getConditionElementAssignment_3(), "rule__EvolutionRule__ConditionElementAssignment_3");
			builder.put(grammarAccess.getEvolutionRuleAccess().getAmountAssignment_4(), "rule__EvolutionRule__AmountAssignment_4");
			builder.put(grammarAccess.getEvolutionRuleAccess().getActionAssignment_6(), "rule__EvolutionRule__ActionAssignment_6");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GameOfLifeDSLGrammarAccess grammarAccess;

	@Override
	protected InternalGameOfLifeDSLParser createParser() {
		InternalGameOfLifeDSLParser result = new InternalGameOfLifeDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GameOfLifeDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GameOfLifeDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
